version: '2'

services:
  mongodb:
    image: mongo:3.6
    ports:
      - 27017:27017
    command: mongod

  bigchaindb:
    depends_on:
      - mongodb
      - tendermint
    image: bigchaindb/bigchaindb:2.0.0-beta5

    environment:
      BIGCHAINDB_DATABASE_BACKEND: localmongodb
      BIGCHAINDB_DATABASE_HOST: mongodb
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
      BIGCHAINDB_WSSERVER_ADVERTISED_HOST: bigchaindb
      BIGCHAINDB_TENDERMINT_HOST: tendermint
      BIGCHAINDB_TENDERMINT_PORT: 26657
    ports:
      - 9984:9984
      - 9985:9985
      - 26658
    command: start
  
  tendermint:
    image: tendermint/tendermint:0.22.8
    entrypoint: ''
    ports:
      - "26656:26656"
      - "26657:26657"
    command: sh -c "tendermint init && tendermint node --consensus.create_empty_blocks=false --proxy_app=tcp://bigchaindb:26658"

  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./public:/usr/src/app/public
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
    environment:
      REACT_APP_BDB_SERVER_URL: "http://localhost:9984"
      REACT_APP_BDB_WS_URL: "ws://localhost:9985"
    ports:
      - "3000:3000"
    command: npm start
